"""Add classification flags to Document

Revision ID: 0315f0f2ef4f
Revises: 073164c13316
Create Date: 2026-08-05 14:42:41.855258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0315f0f2ef4f'
down_revision: Union[str, None] = '073164c13316'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('has_assessments', sa.Boolean(), nullable=True))
    op.add_column('documents', sa.Column('has_topics', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'has_topics')
    op.drop_column('documents', 'has_assessments')
    # ### end Alembic commands ###
