"""phase_2_updates

Revision ID: 381f41da975a
Revises: 
Create Date: 2026-07-18 09:49:40.854590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '381f41da975a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('supabase_uid', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('institution', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('plan', sa.String(length=20), server_default='free', nullable=False),
    sa.Column('plan_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('supabase_uid')
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_supabase_uid', 'users', ['supabase_uid'], unique=False)
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('semester', sa.String(length=50), nullable=False),
    sa.Column('academic_year', sa.String(length=20), nullable=True),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('credit_hours', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('grade_letter', sa.String(length=5), nullable=True),
    sa.Column('grade_scale', sa.String(length=10), server_default='4.0', nullable=False),
    sa.Column('doc_upload_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_courses_semester', 'courses', ['user_id', 'semester', 'academic_year'], unique=False)
    op.create_index('idx_courses_user_id', 'courses', ['user_id'], unique=False)
    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('semester', sa.String(length=50), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='Active', nullable=False),
    sa.Column('is_gpa_goal', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('gpa_target', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_goals_user_id', 'goals', ['user_id'], unique=False)
    op.create_table('streak_daily_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('action_count', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'log_date', name='uq_streak_log_user_date')
    )
    op.create_index('idx_streak_log_user_date', 'streak_daily_log', ['user_id', 'log_date'], unique=False)
    op.create_table('streaks',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_streak_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('on_time_streak_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('longest_activity_streak', sa.Integer(), server_default='0', nullable=False),
    sa.Column('longest_on_time_streak', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_activity_date', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), server_default='lemonsqueezy', nullable=False),
    sa.Column('provider_sub_id', sa.String(length=255), nullable=True),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_sub_id')
    )
    op.create_index('idx_subscriptions_provider_id', 'subscriptions', ['provider_sub_id'], unique=False)
    op.create_index('idx_subscriptions_user', 'subscriptions', ['user_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.String(length=50), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('r2_key', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('processing_status', sa.String(length=50), server_default='pending', nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('r2_key')
    )
    op.create_index('idx_documents_course_id', 'documents', ['course_id'], unique=False)
    op.create_index('idx_documents_sha256', 'documents', ['user_id', 'sha256'], unique=False)
    op.create_table('goal_courses',
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('goal_id', 'course_id')
    )
    op.create_table('gpa_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('semester', sa.String(length=50), nullable=False),
    sa.Column('academic_year', sa.String(length=20), nullable=True),
    sa.Column('entry_type', sa.String(length=20), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('course_label', sa.String(length=255), nullable=False),
    sa.Column('credit_hours', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('grade_letter', sa.String(length=5), nullable=True),
    sa.Column('semester_gpa', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('grade_scale', sa.String(length=10), server_default='4.0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_gpa_entries_semester', 'gpa_entries', ['user_id', 'semester', 'academic_year'], unique=False)
    op.create_index('idx_gpa_entries_user', 'gpa_entries', ['user_id'], unique=False)
    op.create_table('roadmap_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source_document_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('node_type', sa.String(length=100), server_default='Other', nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('weight_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_placeholder', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_confirmed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('extraction_confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('estimated_hours', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('actual_hours', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('confidence_at_creation', sa.SmallInteger(), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='Pending', nullable=False),
    sa.Column('grade', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_roadmap_nodes_course_id', 'roadmap_nodes', ['course_id'], unique=False)
    op.create_index('idx_roadmap_nodes_deadline', 'roadmap_nodes', ['user_id', 'deadline'], unique=False)
    op.create_index('idx_roadmap_nodes_status', 'roadmap_nodes', ['user_id', 'status'], unique=False)
    op.create_index('idx_roadmap_nodes_user_id', 'roadmap_nodes', ['user_id'], unique=False)
    op.create_table('self_assessment_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roadmap_node_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('quality_self_rating', sa.SmallInteger(), nullable=False),
    sa.Column('mood_energy', sa.SmallInteger(), nullable=True),
    sa.Column('reflection_note', sa.Text(), nullable=True),
    sa.Column('hours_before_deadline', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['roadmap_node_id'], ['roadmap_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('roadmap_node_id')
    )
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source_document_id', sa.Integer(), nullable=True),
    sa.Column('linked_node_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('order_index', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_confirmed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['linked_node_id'], ['roadmap_nodes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_topics_course_id', 'topics', ['course_id'], unique=False)
    op.create_index('idx_topics_order', 'topics', ['course_id', 'order_index'], unique=False)
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('roadmap_node_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), server_default='', nullable=False),
    sa.Column('is_stub', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_quick_capture', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['roadmap_node_id'], ['roadmap_nodes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notes_course_id', 'notes', ['course_id'], unique=False)
    op.create_index('idx_notes_roadmap_node', 'notes', ['roadmap_node_id'], unique=False)
    op.create_index('idx_notes_topic', 'notes', ['topic_id'], unique=False)
    op.create_index('idx_notes_user_id', 'notes', ['user_id'], unique=False)
    op.create_table('note_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_note_id', sa.Integer(), nullable=False),
    sa.Column('target_note_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('source_note_id != target_note_id', name='ck_note_links_no_self'),
    sa.ForeignKeyConstraint(['source_note_id'], ['notes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_note_id'], ['notes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_note_id', 'target_note_id', name='uq_note_links_source_target')
    )
    op.create_index('idx_note_links_source', 'note_links', ['source_note_id'], unique=False)
    op.create_index('idx_note_links_target', 'note_links', ['target_note_id'], unique=False)
    op.create_table('topic_completions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('confidence_rating', sa.SmallInteger(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('linked_note_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['linked_note_id'], ['notes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic_id', 'user_id', name='uq_topic_completions_topic_user')
    )
    op.create_index('idx_topic_completions_user', 'topic_completions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_topic_completions_user', table_name='topic_completions')
    op.drop_table('topic_completions')
    op.drop_index('idx_note_links_target', table_name='note_links')
    op.drop_index('idx_note_links_source', table_name='note_links')
    op.drop_table('note_links')
    op.drop_index('idx_notes_user_id', table_name='notes')
    op.drop_index('idx_notes_topic', table_name='notes')
    op.drop_index('idx_notes_roadmap_node', table_name='notes')
    op.drop_index('idx_notes_course_id', table_name='notes')
    op.drop_table('notes')
    op.drop_index('idx_topics_order', table_name='topics')
    op.drop_index('idx_topics_course_id', table_name='topics')
    op.drop_table('topics')
    op.drop_table('self_assessment_logs')
    op.drop_index('idx_roadmap_nodes_user_id', table_name='roadmap_nodes')
    op.drop_index('idx_roadmap_nodes_status', table_name='roadmap_nodes')
    op.drop_index('idx_roadmap_nodes_deadline', table_name='roadmap_nodes')
    op.drop_index('idx_roadmap_nodes_course_id', table_name='roadmap_nodes')
    op.drop_table('roadmap_nodes')
    op.drop_index('idx_gpa_entries_user', table_name='gpa_entries')
    op.drop_index('idx_gpa_entries_semester', table_name='gpa_entries')
    op.drop_table('gpa_entries')
    op.drop_table('goal_courses')
    op.drop_index('idx_documents_sha256', table_name='documents')
    op.drop_index('idx_documents_course_id', table_name='documents')
    op.drop_table('documents')
    op.drop_index('idx_subscriptions_user', table_name='subscriptions')
    op.drop_index('idx_subscriptions_provider_id', table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_table('streaks')
    op.drop_index('idx_streak_log_user_date', table_name='streak_daily_log')
    op.drop_table('streak_daily_log')
    op.drop_index('idx_goals_user_id', table_name='goals')
    op.drop_table('goals')
    op.drop_index('idx_courses_user_id', table_name='courses')
    op.drop_index('idx_courses_semester', table_name='courses')
    op.drop_table('courses')
    op.drop_index('idx_users_supabase_uid', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
