"""add_percentage_to_gpa_entries

Revision ID: 073164c13316
Revises: c9e1a4f72b38
Create Date: 2026-07-28 13:41:57.608267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '073164c13316'
down_revision: Union[str, None] = 'c9e1a4f72b38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gpa_entries', sa.Column('percentage', sa.Numeric(precision=5, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gpa_entries', 'percentage')
    # ### end Alembic commands ###
